name: Test Cron

on:
  schedule:
    - cron: "*/5 * * * *"   # cada 5 minutos (m√≠nimo permitido)

jobs:
  echo-date:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar fecha/hora
        run: date
